- name: Create .env on EC2
  run: |
    ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
      cd /home/${{ secrets.EC2_USER }}/node-app
      echo "PORT=${{ secrets.PORT }}" > .env
      echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
      echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> .env
      echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
      echo "CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}" >> .env
      echo "CLOUDINARY_API_SECRET_KEY=${{ secrets.CLOUDINARY_API_SECRET_KEY }}" >> .env
      echo "CLOUDINARY_NAME=${{ secrets.CLOUDINARY_NAME }}" >> .env
      echo "CORS_ORIGIN=${{ secrets.CORS_ORIGIN }}" >> .env
      echo "NODE_ENV=production" >> .env

      npm install
      # pm2 restart all || pm2 start src/index.js --name my-app
    EOF
