name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create .env file from secrets
      run: |
        echo "CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}" >> .env
        echo "CLOUDINARY_API_SECRET_KEY=${{ secrets.CLOUDINARY_API_SECRET_KEY }}" >> .env
        echo "CLOUDINARY_NAME=${{ secrets.CLOUDINARY_NAME }}" >> .env
        echo "CORS_ORIGIN=${{ secrets.CORS_ORIGIN }}" >> .env
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
        echo "PORT=${{ secrets.PORT }}" >> .env
        echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
        echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> .env
        echo "SESSION_SECRET=${{ secrets.SESSION_SECRET }}" >> .env
        echo "TWILIO_ACCOUNT_SID=${{ secrets.TWILIO_ACCOUNT_SID }}" >> .env
        echo "TWILIO_AUTH_TOKEN=${{ secrets.TWILIO_AUTH_TOKEN }}" >> .env
        echo "TWILIO_SMS_NUMBER=${{ secrets.TWILIO_SMS_NUMBER }}" >> .env

    - name: Upload .env to server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        source: ".env"
        target: "~/"

    - name: SSH into server and deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd ~/Hubbly_backend || git clone https://github.com/Hasham99/Hubbly_backend && cd Hubbly_backend
          pm2 stop hubbly_backend || true
          cd ..
          rm -rf Hubbly_backend
          git clone https://github.com/Hasham99/Hubbly_backend
          cd Hubbly_backend
          mv ~/".env" .
          npm install
          pm2 start src/index.js --name hubbly_backend
          pm2 save
