name: Deploy to EC2 and Create .env

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to EC2 and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          envs: CLOUDINARY_API_KEY,CLOUDINARY_API_SECRET_KEY,CLOUDINARY_NAME,CORS_ORIGIN,DATABASE_URL,PORT,SUPABASE_KEY,SUPABASE_URL
          script: |
            cd /home/ubuntu

            if [ ! -d "Hubbly_backend" ]; then
              git clone https://github.com/${{ github.repository }}.git Hubbly_backend
            fi

            cd Hubbly_backend
            git pull origin main

            # ✅ Use environment variables directly from GitHub secrets
            cat <<EOF > .env
CLOUDINARY_API_KEY=$CLOUDINARY_API_KEY
CLOUDINARY_API_SECRET_KEY=$CLOUDINARY_API_SECRET_KEY
CLOUDINARY_NAME=$CLOUDINARY_NAME
CORS_ORIGIN=$CORS_ORIGIN
DATABASE_URL=$DATABASE_URL
PORT=$PORT
SUPABASE_KEY=$SUPABASE_KEY
SUPABASE_URL=$SUPABASE_URL
EOF

            npm install

            if pm2 list | grep -q "hubbly_backend"; then
              pm2 restart hubbly_backend
            else
              pm2 start src/index.js --name hubbly_backend
            fi
