name: Deploy to EC2 and Create .env

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to EC2 and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            # Move to home directory
            cd /home/ubuntu

            # Clone the project if not already cloned
            if [ ! -d "Hubbly_backend" ]; then
              git clone https://github.com/${{ github.repository }}.git Hubbly_backend
            fi

            cd Hubbly_backend

            # Pull the latest code
            git pull origin main

            # Create or overwrite .env
            cat > .env <<EOF
CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}
CLOUDINARY_API_SECRET_KEY=${{ secrets.CLOUDINARY_API_SECRET_KEY }}
CLOUDINARY_NAME=${{ secrets.CLOUDINARY_NAME }}
CORS_ORIGIN=${{ secrets.CORS_ORIGIN }}
DATABASE_URL=${{ secrets.DATABASE_URL }}
PORT=${{ secrets.PORT }}
SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}
SUPABASE_URL=${{ secrets.SUPABASE_URL }}
EOF

            # Install dependencies
            npm install

            # Start or restart the app with pm2
            if pm2 list | grep -q "hubbly_backend"; then
              pm2 restart my-app
            else
              pm2 start src/index.js --name hubbly_backend
            fi
