name: Deploy Node App to EC2 and Upload .env

on:
  push:
    branches:
      - main  # Trigger deploy on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Create the .env file locally on the GitHub runner
      - name: Create .env file
        run: |
          echo "CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}" > .env
          echo "CLOUDINARY_API_SECRET_KEY=${{ secrets.CLOUDINARY_API_SECRET_KEY }}" >> .env
          echo "CLOUDINARY_NAME=${{ secrets.CLOUDINARY_NAME }}" >> .env
          echo "CORS_ORIGIN=${{ secrets.CORS_ORIGIN }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> .env
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
          cat .env  # Verify that the .env file has been created

      # Step 3: Transfer the .env file to EC2 using SCP
      - name: Copy .env to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: ".env"
          target: "/home/ubuntu/Hubbly_backend/.env"
          debug: true  # Enable debug logging for more detailed error info

      # Step 4: SSH into EC2 and deploy the app
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/Hubbly_backend

            # Pull latest code
            git pull origin main

            # Install dependencies
            npm install

            # Restart or start the app with pm2
            if pm2 list | grep -q "hubbly_backend"; then
              pm2 restart hubbly_backend
            else
              pm2 start src/index.js --name hubbly_backend
            fi
